### PR TITLE
496 - adds changelog on startup

### PR DESCRIPTION
**Pull request by crankycoder**
I've added a changelog on startup.

The changelog is not localized as we currently do not have a process to do localization prior to a new release.

### CODE REVIEW

**Comment by crankycoder** [comment]
@garvankeeley travis died on grabbing one of the dependencies. blargh.

**Comment by garvankeeley** [comment]
The bulleted list can be done in strings.xml
For example:
`<string name="whats_new"><li>More conservative power saving options</li>`
`\n<li>Home screen widget</li>`
`\n<li>Wifi blocklist updates</li></string>`

Will look like this:
https://www.dropbox.com/s/6iv4npwu19rwaov/Screenshot%202015-01-21%2018.25.27.png

**Comment by garvankeeley** [comment]
Needs to be wrapped in a scrollview, for scrolling

**Comment by garvankeeley** [comment]
I am thinking we shouldn't show it on first run, rather than have 2 dialogs at startup. First-run users are less concerned with new features.

**Comment by crankycoder** [comment]
I've disabled the firstrun changelog thing. Scrollview isn't needed as AlertDialog will automatically scroll if the text overflows vertically.  I think that's everything.

**Comment by cascheberg** [comment]
I have some comments:
- you can also move the "OK" to the `strings.xml`
- I guess you can now completely remove the `dialog_whatsnew.xml`
- shouldn't it be "What's new" (instead of "Whats new")?

**Comment by crankycoder** [comment]
@garvankeeley this should merge cleanly now.  You can test by using the diff @ version afa5c1a where I commented out the pref update to ensure that the changelog displays once and only once, but not on first run.

@cascheberg thanks for the review - layout XML file has been dropped and strings have been updated.

**Comment by garvankeeley** [comment]
One more thing, if the strings.xml name="whats_new" is blank, the dialog shouldn't show. In case we don't want it to show. (Maybe it does this, I haven't looked)

**Comment by crankycoder** [comment]
Added the check for whats_new text length in 48c5b9d.  

Dang it.  There are no tests for MainDrawActivity.  I'm going to add a test in a separate PR.

**Comment by garvankeeley** [comment]
This didn't scroll for me when I tried, are you sure this is supposed to work? (I rotated the screen one the dialog was showing, and not all lines were shown any more, and I couldn't scroll)

**Comment by crankycoder** [comment]
Hrm.  Here's two screenshots where I copy/pasted the sample text several times.  

The bottom screenshot is where I've scrolled down to the bottom - you can see the scrollbar on the right hand side.

screenshot_2015-01-27-08-34-12
screenshot_2015-01-27-08-34-23

**Comment by crankycoder** [comment]
Bah. This works on both the OnePlus and Moto G over here.  I'll try with the Nexus 4 running Lollipop.

**Comment by crankycoder** [comment]
Works for me on Lollipop on the Nexus 4.

**Pull request merged**
