### PR TITLE
Add Catalan translation.

### PR DESCRIPTION
**Pull request by lua86**
I do not know anything about coding -yet-, but I hope I added all needed for the Catalan translation being usable.

### CODE REVIEW

**Comment by cpeterso** [comment]
@lua86: Thanks for the Catalan translation. Can you please fix these errors in your values.xml file? The apostrophe is a special character in Android's translation files, so you need to "escape" it using a backslash like `Servei de reconeiximent d\'activitat de Mozilla Stumbler`.

```
res/all/debug/values-ca/values.xml:13: error: Apostrophe not preceded by \ (in Servei de reconeiximent d'activitat de Mozilla Stumbler)
res/all/debug/values-ca/values.xml:30: error: Apostrophe not preceded by \ (in Temps de l'ùltima càrrega: %1$s)
res/all/debug/values-ca/values.xml:34: error: Apostrophe not preceded by \ (in Mode d'estalvi d'energia)
res/all/debug/values-ca/values.xml:35: error: Apostrophe not preceded by \ (in Quan activat, només s'escanejarà quan es mou)
res/all/debug/values-ca/values.xml:47: error: Apostrophe not preceded by \ (in Punts d'accés WiFi visibles: %1$d)
res/all/debug/values-ca/values.xml:48: error: Apostrophe not preceded by \ (in Punts d'accés WiFi escanejats: %1$d)
```

**Comment by cpeterso** [comment]
Also, when you've fixed and committed your value.xml file, can you please use `git rebase` to squash your branch's commits into a single commit? Here are instructions for squashing git commits: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by lua86** [comment]
So, first fixing apos and committing, then squashing the old commits with rebase, then pushing. And then?

**Comment by lua86** [comment]
Well I tried. I hope I didn't make much of a mess.

**Comment by cpeterso** [comment]
hi @lua86, I've fixed the apostrophe problem, but can you please squash your intermediate commits into one commit? I think you need to:
1. `git rebase --interactive HEAD~4`
2. Change the last three `pick`s to `fixup` for "Fixing Catalan Translation", "Merging Upstream" and "Remove Catalan translation strings backup". Leave the first `pick` for "Add Catalan translation." git will then squash all four commits into one called "Add Catalan translation."
3. Then `git push --force` your branch to update your GitHub repo and this pull request should automatically be updated.

**Comment by lua86** [comment]
GNU nano 2.2.6                Fitxer: /home/lua/MozStumbler/.git/rebase-merge/git-rebase-todo                                         

pick 0b967e2 Optionally use the new getAllCellInfo API (#72)
pick 31e8aa1 Add Catalan translation.
pick 56ff399 Added Italian translation
pick 6048a71 Added Italian translation
#I cannot find my intermediate commits. Seems I got messed up. Or maybe did something weird to my local repo.

**Comment by cpeterso** [comment]
@lua86: I don't think you messed up your repo. I still see all your commits. I will just merge them as-is. Thanks for your help and patience!

**Comment by lua86** [comment]
I meant I messed up my local copy. Also, thank you for your patience. Now I should learn more about git, github, and Android 'special' things with xml...

**Pull request merged**
