### PR TITLE
Updated translations

### PR DESCRIPTION
**Pull request by Djfe**
Removed quit translation from all translations and aligned the translations to the English source.
Added comments to show missing translations.
Added line-breaks if missing.

### CODE REVIEW

**Comment by rodmoreno** [comment]
For the translation into Spanish, had already updated the strings in #508

**Comment by Djfe** [comment]
Sorry, haven't really thought about it as I saw your translation
Could you remove the quit string from your translation, please?

I will revert changes in the Spanish translation later ;)

**Comment by rodmoreno** [comment]
@Djfe Done!

**Comment by cpeterso** [comment]
@Djfe: I merged @rodmoreno's PR #505 for values-es to master. Can you please rebase your PR onto the current master to see if the Travis CI build will then compile correctly? Also, can you use `git rebase --interactive` to squash all your small commits into a single commit?

**Comment by Djfe** [comment]
Have to update it anyways due to the new scan_always strings.

Is there a way to do git rebase --interactive over the web interface?

**Comment by cpeterso** [comment]
@Djfe: I don't know, but probably not. I didn't even know that GitHub had a web editing interface! :)

**Comment by Djfe** [comment]
Are you using the desktop application to do the rebase?

**Comment by cpeterso** [comment]
@Djfe: I rebased your PR and merged it as commit f055c415bde3f47842e6b835dc04f7017a8d899b.

**Comment by Djfe** [comment]
thx ;)
Just wanted to redo it all because I got frustrated with the git shell.

**Pull request closed without merging**
