### PR TITLE
Save on disk + sync adapter

### PR DESCRIPTION
**Pull request by illarionov**
1. Save data to be sent on disk (in the sqlite database)
2. Use the sync adapter for data uploading
3. Add "Upload observations" dialog (#250, #196)

### CODE REVIEW

**Comment by cpeterso** [comment]
@illarionov, this looks great! This is a lot of code, so I have a few questions. You might want to answer my questions as big comments in the code itself. :)

Can you please describe the advantages of using the sync adapter? How often will the sync adapter upload and how does it interact with "Upload only WiFi"?

Can you please describe the schema of the database tables? AFAICT, we are storing a JSON list of multiple reports in each TABLE_REPORTS row. Can we just store one report or observation per database row? That seems a lot simpler. Batching up `RECORD_BATCH_SIZE` number of reports in `mReports` before flushing them to the Pref store has always been an extra layer of confusion and bugs. `RECORD_BATCH_SIZE` was originally added to throttle network uploads, but it later started throttling writes to the Pref store. I'd love if we could remove all the batching code and just write each report to the database. :)

Why do we need remember a RETRY_NUMBER for each report?

**Comment by illarionov** [comment]
Synchronization adapter was chosen rather inspired by the video on the android developers channel: [Efficient Data Transfers](http://www.youtube.com/watch?v=5onKZcJyJwI) :)
It schedules data transfers in conjunction with transfers from other apps and theoretically this can reduce overall battery usage. And also you do not need to monitor the network connection.
The only drawback I found is that a our stub account is added to the list of accounts in the device settings, and it is not possible to hide it.

Synchronization service is notified by the provider every 10 queued reports (`SYNC_REPORTS_PERIOD`). When `RECORD_BATCH_SIZE=40`, it is about every 3-5 minutes.
Adapter executes sync not immediately.

On stop scanning (or when user clicks "upload" button) the immediate sync is requested.
If "Upload only WiFi" is activated and Wi-fi is not available, the `onPerformSync()` will fail with numIoExceptions=1 and sync adapter should re-schedule this sync.

The scheme all true. `TABLE_REPORTS` is a send queue. Each row is a single JSON request to the server with the measurements.
- `report`  - JSON payload.
- `observation_count`, `cell_count`, `wifi_count` - is all statics about this request.
- `retry` - retry number.

When the server returns a success or returns a fatal error, the row is removed from the database.
On the temporary error, this counter is incremented and query is re-executed on the next sync. But not more than `MAX_RETRY_COUNT` times. That is, the `retry` counter is used so as not to keep a record in the database forever.

`TABLE_STATS` is a simple key-value database with counters of data that is already sent: last upload time, number of observations/cells/wifi sent. I have not used SharedPreferences there because SharedPreferences does not work between 2 processes [on android 2.3](http://stackoverflow.com/a/12144418).

I have left all the batching logic to reduce the number of inserts, rows and overall load on the
database. Although now I also think that this optimization may be neglected in order to simplify the code. I will try to rewrite this part in a few days.

**Comment by tamcap** [comment]
If I can add anything to the discussion: let's give users an option to keep the records in the db despite being sent - that was one of the original motivations behind local storage anyway (so that they can be plotted locally).

Also [edited]: would you be willing to put in lat / lon in the rows too? I mean outside the json string, as 2 separate fields (float/int).

**Comment by illarionov** [comment]
I think it is better to make a separate table for this. Although, I do not really like the idea to implement a functionality of the GPS tracker in this application.

**Comment by tamcap** [comment]
To be honest, neither do I...

**Comment by illarionov** [comment]
Indeed, one of the advantages of the scheme 'observation per database row' will be coordinates in the separate fields. It even may be possible to merge two measurements on the same location (but at the different time) into the one.  Although I'm not sure about performance

**Comment by tamcap** [comment]
I wonder if we could off-load some of the deduplication off ichnaea this way. @hannosch mentioned that some BSSIDs have thousands if not millions of observations already. There is no reason to report the same location 100 times with 10 networks that never changed.

**Comment by cpeterso** [comment]
I like @illarionov's approach to log the observation reports because the server may, in the future, be able to make use of which APs are observed at the same time, not just the observed lat/lon of individual APs. While creating a table of individual APs will be interesting for some use cases, I don't think this PR should implement it.

I don't think having a MozStumbler sync provider listed in the system settings' list of sync accounts is a problem.

@illarionov: do you think I should merge this PR now or should I wait for you to remove the batching code? I'd like someone to remove batching code at some point, but I don't want this PR to bit-rot if there are merge conflicts from other PRs.

**Comment by illarionov** [comment]
It would be better to merge this PR in the current state. I can not say for sure when my new revision will be ready.

**Comment by tamcap** [comment]
Sooo... I cannot build this pr. The `:compileDebugAidl` breaks down by trying to AIDL-interpret the additional .java files (which is something I noticed earlier, and briefly mentioned on IRC). Any ideas how to fix it?

**Comment by cpeterso** [comment]
@tamcap: I can build this PR, but I remember when you and I discussed this same `:compileDebugAidl` problem earlier. Are you build using the `./gradlew` script in the MozStumbler repo?

**Comment by tamcap** [comment]
I made a fresh clone just before the commit a90dad0 merger, then `./gradlew build` --> ok; subsequent `git pull` got the commit a90dad0 and `./gradlew build` failed on `:compileDebugAidl`. 

Another fresh clone later, everything builds just fine... o_0

**Comment by Djfe** [comment]
Thank you very much illarionov!
I really like those changes ;)

**Comment by tamcap** [comment]
I was able to combat `:compileDebugAidl` problems by invoking `./gradlew clean` explicitly in the existing sources. Strange. But works.

**Pull request merged**
