### PR TITLE
Feature/adapt to small screens

### PR DESCRIPTION
**Pull request by santiago-hollmann**
Changes:
- Added project.properties to .gitignore
- Updated on gradle.build the BuildToolVersion
- Added libs osmdroid, slf4j and support-v4 to make it run easily from Eclipse
- Small changes on landscape and portrait main activity UI to make it fit on small devices (such us Galaxy Y) which are incredible common in India and Brazil.

### CODE REVIEW

**Comment by garvankeeley** [comment]
Thanks, I have a few favours to ask. Can you screenshot the before and after so we can see what the changes are? Also can you just commit 68fe15c, your changes to the layouts? 
There is issue #633 for upgrading gradle.

**Comment by garvankeeley** [comment]
For just the main activity, I tried to make sure nothing was cut off:
https://github.com/mozilla/MozStumbler/pull/648

I didn't look at the other screens you have proposed fixes for.

**Comment by santiago-hollmann** [comment]
I am travelling so I am not able to do this until I come back on July 6th. Cheers and thanks for your feedback

**Comment by garvankeeley** [comment]
@santiago-hollmann I hope it is ok that I close this, there have been some UI updates for small screens, issue #648 and also issue #666. Can you grab the latest build and see how it looks on your device? Thanks.

**Pull request closed without merging**
