### PR TITLE
Update zh-tw l10n; typo fix

### PR DESCRIPTION
**Pull request by petercpg**

### CODE REVIEW

**Comment by petercpg** [comment]
Just noted Play Store listing translation Issues for multiple locales, do we need Chinese as well?

**Comment by petercpg** [comment]
Oops, it seems travis-ci stuck on fetching library dependencies...

**Comment by crankycoder** [comment]
Dang it.  I've restarted the build.  Travis failures aren't uncommon anymore.  Going to take a poke at making this less terrible.

**Comment by crankycoder** [comment]
Thanks @petercpg !

**Pull request merged**
