### PR TITLE
Updating build.gradle as per  #1202

### PR DESCRIPTION
**Pull request by aishraj**
Making the change as per #1202 Capture buildhost in versionName
Please review it accordingly. From my understanding, the Updater which uses the versions seems to work fine. Kindly suggest if anything else might be under the scope of this change .

### CODE REVIEW

**Comment by crankycoder** [comment]
I think this needs some changes to the Updater.java code as it's naive and assumes integers in each part of the version name. 

The use of a raw hostname is probably unsafe as well, I think we want to restrict the characters with a regular expression to just [a-z] and maybe [_-].

**Comment by aishraj** [comment]
@crankycoder I've added a few rudimentary checks for sanitizing the hostname check in both the Updater and the gradle config. Let me know if it looks good to you.

**Comment by garvankeeley** [comment]
make debug now fails for me:
- Where:
  Build file '/Users/gkeeley/c/github/mz-passive-stumbler/MozStumbler/android/build.gradle' line: 5
- What went wrong:
  A problem occurred evaluating project ':android'.
  
  > gkeeley13311: gkeeley13311: nodename nor servname provided, or not known

**Comment by aishraj** [comment]
I have not attempted to reproduce the behaviour yet. However it looks like it may be related to a bug while performing hostname lookup on OSX with JDK 7 [link here](https://coderwall.com/p/ktbkea/play-framework-2-error-nodename-nor-servname-provided-or-not-known) I will  nevertheless try to reproduce it on my Linux machine and provide an update on it later.

**Comment by crankycoder** [comment]
Hotfix applied in https://github.com/mozilla/MozStumbler/commit/ec3f306b0ed8b18888c0290de54e775b58f5e1e6

**Pull request merged**
