### PR TITLE
Fixed handling for unknown location state.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dougt** [comment]
Freekzy, can you rebase?  I think I just want 97c9a6bb4fa0c035fe5a596ea4fb6ec6fe3a4396, right?  But not totally sure.

**Comment by ghost** [comment]
Yes, only 97c9a6b.

**Comment by ghost** [comment]
@dougt, can you cancel pull request? It's my fault with master branch. Damn :(

**Comment by cpeterso** [comment]
Closing PR at @freekzy's request.

**Pull request closed without merging**
