### PR TITLE
Add Information (GPS Status, Location, Cell Info, WiFi Info) to the Map

### PR DESCRIPTION
**Pull request by keverets**
This adds the translucent header bar, and solid bottom info bar similar to those in the mocks.

The icons come from https://www.iconfinder.com/icons/175171/gps_receiving_icon then were modified, so if used will need to include link to author's website somewhere: http://icons8.com/

### CODE REVIEW

**Comment by garvankeeley** [comment]
Looks amazing. Almost have the map view functional as the main screen once the coverage overlay is bug free.

screenshot_2014-07-28-00-06-36

**Comment by garvankeeley** [comment]
BTW, will review in more detail and merge, I just patched my branch quickly to see it in action

**Comment by garvankeeley** [comment]
Can I manually merge, or do you want to rebase? Hand-merging this PR is trivial

**Comment by keverets** [comment]
Rebased.  Feel free to hand-merge if that works for you in the future.

**Comment by garvankeeley** [comment]
Thanks Kevin!

**Pull request merged**
