### PR TITLE
Basic geofencing.

### PR DESCRIPTION
**Pull request by tamcap**
This very basic interface allows to specify a point (in a format of `-10.005,10.02`) around which MozStumbler will not report the results. Exclusion zone is currently defined as +/- 0.01 deg lat/lon.

Geofencing works good :+1:

### CODE REVIEW

**Comment by cpeterso** [comment]
@tamcap: should I be reviewing this "Basic geofencing" pull request or the `better_geofencing` branch in your tamcp/MozStumbler repository?

**Comment by tamcap** [comment]
This is the basic functionality. Geofencing will work with commit f405761, everything else is just extra features / UI. I think the best way forward is to review this and then any changes will derive from here. If there are some serious (low-level) changes you want to make, I will implement them in both places.

**Comment by tamcap** [comment]
Do you think it's ok to invoke `Prefs.getLat()` and `Prefs.getLon()` everytime `contains()` is called? That was my original motivation for passing it down from GPSScanner.

**Comment by tamcap** [comment]
There are 2 exceptions I am worried about: `NumberFormatException` and `IndexOutOfBounds` (coming from `Substring()`. I will catch them both and just abort in that case.

**Comment by tamcap** [comment]
No complaints on the implicit float + string.

**Comment by tamcap** [comment]
It seems we are moving forward with the more involved geofencing, this pull request can be closed.

**Pull request closed without merging**
