### PR TITLE
Update Android SDK to 22.0.5, Build Tools to 18.0.1, and API Level to 18

### PR DESCRIPTION
**Pull request by cpeterso**
Android Build Tools 18.0.0 are no longer available in Google's Android SDK Manager GUI, so update to 18.0.1.

### CODE REVIEW

**Comment by stephanenicolas** [comment]
Thanks for this example guys. Where did you learn build tools were available on its download url ? I searched the docs and found nothing.

**Comment by cpeterso** [comment]
@stephanenicolas: running the Android SDK Manager updater (i.e. the `android` command-line utility) notified me that a build tools update was available.

**Comment by stephanenicolas** [comment]
@cpeterso I didn't see the URL of download of the build tools... Was it really given ?

**Comment by cpeterso** [comment]
@stephanenicolas: sorry, I misread your original question. The Android SDK Manager did not give the new download URL; I just guessed. <:) I took download URLs on the Android website and changed the version number in the URL.

**Comment by stephanenicolas** [comment]
Ok :) Nice guess, You saved my day yesterday :)

But, shouldn't we open an issue on ADT so that the Android team makes it
more friendly to have Travis builds ?
How could we turn the issue to make it more general and give the Android
team interest in it ?

Stéphane

2013/9/16 Chris Peterson notifications@github.com

> @stephanenicolas https://github.com/stephanenicolas: sorry, I misread
> your original question. The Android SDK Manager did not give the new
> download URL; I just guessed. <:) I took download URLs on the Android
> website and changed the version number in the URL.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dougt/MozStumbler/pull/52#issuecomment-24543043
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Pull request merged**
