### PR TITLE
Support RTL

### PR DESCRIPTION
**Pull request by xsoh**
Supporting RTL for API 18 or above

### CODE REVIEW

**Comment by tamcap** [comment]
Interesting! http://developer.android.com/guide/topics/manifest/application-element.html#supportsrtl

**Comment by xsoh** [comment]
@tamcap : oh my bad, I wrote API 18. It should be 17. 

Why is there an error for the build?

**Comment by tamcap** [comment]
The error is unrelated to your pull request. If you rebase (and squash too, to make things pretty!) your commits on the current master, the Travis error will go away.

**Comment by cpeterso** [comment]
@xsoh: I rebased your RTL changes into a new branch (PR #535) to fix the (unrelated) build errors. Thanks for your code contribution! Sorry for the long delay.

**Pull request closed without merging**
