### PR TITLE
Update translations

### LINKED ISSUE #1257: Minor settings UI items: Crash Reports title and change to MLS detailed info
- Title for crash reports section:
  *\* just "Crash reports", or something in the direction of "Feedback" / "Support". Firefox has "Data Choices".
- detailed info for MLS location:
  "At the cost of a bit more energy, memory and network usage, the MLS location is shown for each report. This is shown on the map as a red dot for the MLS location, with a line to its report. However, it will not query locations over mobile data connections if \"%1$s\" is enabled."

### PR DESCRIPTION
**Pull request by cascheberg**
This fixes #1257 and updates German translations

### CODE REVIEW

**Comment by Djfe** [comment]
Ich fand Auflösung besser
Ansonsten: "Mehr Details" und "Weniger Details"

Es gibt keine hohen oder niedrigen Details, das klingt einfach falsch ;)

**Comment by cascheberg** [comment]
OK, changed back to "Auflösung".
I wasn't sure about the wording either, but "Hohe Details" seems to be quite common when talking about computer game settings. I think "Mehr Details" is also not quite perfect.

**Comment by Djfe** [comment]
wording is always complex, but everybody should understand "Auflösung"
"Mehr/Weniger Details" might not suggest that it is about the resolution
it could also be something like showing less street names and stuff like that (which of course is the case, but it's because of the lower zoom level that is being used to get the lower resolution)

**Comment by garvankeeley** [comment]
Looks good

**Pull request merged**
