### PR TITLE
Use public notifications feature on Android 5

### PR DESCRIPTION
**Pull request by cascheberg**
Follow up to #1341
@garvankeeley is this working for you?

### CODE REVIEW

**Comment by garvankeeley** [comment]
Not sure what you are asking, what does this change do? Does it show the notification in a different place?

**Comment by cascheberg** [comment]
With this patch the notification text becomes visible on the Android 5 lock screen as well.

I was referring to this error that you mentioned:

> Error: uses-sdk:minSdkVersion 10 cannot be smaller than version L declared in library com.android.support:support-v4:21.0.0-rc1

(The Travis build failed, apparently it does not have the new support library version available yet.)

**Comment by cascheberg** [comment]
I updated the PR to make it pass. It now uses

> com.android.support:support-v4:21.0.+

instead of

> com.android.support:support-v4:21.0.3

**Comment by garvankeeley** [comment]
Works great!

**Pull request merged**
