### PR TITLE
add build and os info to user agent

### PR DESCRIPTION
**Pull request by garvankeeley**
Looks like this:
google/hammerhead/hammerhead:4.4.4/KTU84P/1227136:user/release-keys__MozStumbler/0.40.0.0

### CODE REVIEW

**Comment by garvankeeley** [comment]
@hannosch any preference as to how this is formatted?

**Comment by hannosch** [comment]
A typical Android example is: `"Dalvik/1.6.0 (Linux; U; Android 4.1.2; DROID RAZR Build/9.8.2O-72_VZW-16-5)"`. Knowing the Android version and device type is really useful. So I'd use something like this and append `MozStumbler/0.40.0` to it.

For example:

`"Dalvik/1.6.0 (Linux; U; Android 4.1.2; DROID RAZR Build/9.8.2O-72_VZW-16-5) MozStumbler/0.40.0"`

Edited: Use slash between product / version, as per http://tools.ietf.org/html/rfc7231#section-5.5.3

**Comment by garvankeeley** [comment]
The device type is there 'hammerhead', the build '4.4.4/KTU84P/1227136', what part should I change? Is it the string formatting that should change?

Here are the available fields:
http://ec2-54-172-135-65.compute-1.amazonaws.com/acralyzer/_design/acralyzer/index.html#/report-details/stumbler/053af68c-9941-4807-9afd-d85b4cf967aa
No shortage of them :)

**Comment by garvankeeley** [comment]
According to StackOverflow this will do it. Which would be MozStumbler-only due to the heavy weight approach.
String ua = new WebView(this).getSettings().getUserAgentString();

**Comment by garvankeeley** [comment]
Fennec stumbler is like so:
Mozilla/5.0 (Android; Mobile; rv:35.0a1) Gecko/35.0a1 Firefox/35.0a1

I could append the "FINGERPRINT" string, which is like so:
motorola/falcon_retuglb/falcon_umts:4.4.3/KXB21.14-L1.32/33:user/release-keys

But it seems a tad verbose. I would be happy with device (falcon_umts) and version (4.4.3)

**Comment by garvankeeley** [comment]
new pr opened

**Pull request closed without merging**
