### PR TITLE
Set map gps/cell/wifi info to zero if not scanning actively

### LINKED ISSUE #1436: paused mode should set gps/wifi/cell values to zero
this is an issue that was brought up in #1322

since the device isn't scanning anything in paused mode those values probably should be set to zero to avoid confusion

### PR DESCRIPTION
**Pull request by cascheberg**
Fixes #1436

### CODE REVIEW

**Comment by crankycoder** [comment]
Use the intent. I'm removing the service pointer.

**Comment by cascheberg** [comment]
@crankycoder Which intent? Can you already tell when your changes will be ready to be merged?

**Comment by crankycoder** [comment]
The persistedstats class emits an intent for metrics that gets picked up by
the metrics view.

Can you do something similar so that we aren't reliant on a pointer to the
service? We're moving to using an unbound service for both active and
passive stumbling.

**Comment by crankycoder** [comment]
You know what, I'm going to change tact for #1479 so that I don't have to hold patches like this up. I'll send you a small patch to this PR so that we can get this fix in shortly.

**Comment by cascheberg** [comment]
PR updated

**Comment by crankycoder** [comment]
Were you able to reliably reproduce a bug?

**Comment by cascheberg** [comment]
@crankycoder What exactly are you asking? The PR fixes #1436, which is a minor cosmetic issue. The updated PR is rebased and I changed the way the displayed GPS satellites are set to zero.

Aside from that, I think the UI update methods are a bit messy. Could we remove `updateUiOnMainThread` and put more dedicated intent receivers directly into `MainDrawerActivity`?

**Comment by crankycoder** [comment]
Thanks!

**Comment by crankycoder** [comment]
This fixes the lag in #1567

**Pull request merged**
