### PR TITLE
Always update metrics last upload time

### PR DESCRIPTION
**Pull request by cascheberg**
The last upload time shown in metrics is not an absolute value anymore, so it needs to be updated continuously.

### CODE REVIEW

**Comment by garvankeeley** [comment]
Is there a solution that doesn't require reading the sync stats from disk. This updating of the last upload time could be separate from updateSyncStats() function entirely, as is isn't related to sync, it is purely a UI thing, updating a label based only on the existing value of the label and the current time.

**Comment by cascheberg** [comment]
I see. I'm sure I can improve this then. How about using `final long bytesUploadedThisSession = AsyncUploader.sTotalBytesUploadedThisSession.get();` to check for updates (as before) and then caching the `lastUploadTime`?
I think this method is called whenever metrics are updated, so this includes updates on cell and wifi scans. That could also be improved if still necessary.

**Comment by garvankeeley** [comment]
If the scanning isn't running, the label should still update. How about a posting an event every 10 seconds (handler.postDelayed) to update the label, updateLastUploadedLabel() which will update based on mLastUploadTime

**Comment by cascheberg** [comment]
I think I got it, PR updated

**Comment by garvankeeley** [comment]
Nice! thanks

**Pull request merged**
