### PR TITLE
Added highlight when tapping locate me button.

### PR DESCRIPTION
**Pull request by garvankeeley**

### CODE REVIEW

**Comment by crankycoder** [comment]
Oh, you love fixing icons.

**Comment by crankycoder** [comment]
Can we change this at all to stay highlighted as the centering is corrected?  I can barely see the highlight as it goes off immediately once my fat finger leaves the button.

**Comment by garvankeeley** [comment]
For you, more highlights.

**Comment by crankycoder** [comment]
Now stop playing with gimp.

**Pull request merged**
