### PR TITLE
Add Wi-Fi Access Points scanning option

### PR DESCRIPTION
**Pull request by xsoh**
Adding Wi-Fi Access Points scanning in setting for enhancement on #241

### CODE REVIEW

**Comment by cpeterso** [comment]
@xsoh: thanks for your pull request! Your fix looks good, but I just thought of an alternate solution after rereading @vinitraje's issue #241.

Instead of adding a new preference and UI, could we just change `WifiScanner` to check whether the phone's Wi-Fi is enabled? @vinitraje's original concern was that MozStumbler would enabled Wi-Fi. `WifiScanner.start()` could check if Wi-Fi is disabled and then return early without doing anything. With my proposed solution, the user could disable their phone's Wi-Fi if they didn't want to scan Wi-Fi access points.

**Comment by vinitraje** [comment]
@cpeterso That's what I was trying to say. Instead of turning ON Wi-Fi every time, scan only when Wi-Fi is turned ON by user.

And make the reporting independent of Wi-Fi status. Because now when we try to scan with Wi-Fi turned off MozStumbler won't  send any reports until Wi-Fi is turned back ON.

**Comment by xsoh** [comment]
@cpeterso  & @vinitraje Thanks for reporting! I'll try to do it.

**Comment by cpeterso** [comment]
@xsoh: Looks great! To keep our git revision history "clean", can you please "squash" your three separate commits into one? You can use `git rebase --interactive`, but here is a simpler method. The first command will "uncommit" your three commits. The second command will then re-commit them as one single commit with the new commit message.

```
git reset --soft HEAD~3
git commit -m "Don't scan when Wi-Fi turned off"
```

Here is a good tutorial about using git rebase to "squash" multiple commits into one: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by xsoh** [comment]
Oops, Sorry I'm new to git :S

**Comment by cpeterso** [comment]
Looks good. Thanks for your help, @xsoh! :)

**Pull request merged**
