### PR TITLE
Add passive location listener to MapLocationListener

### LINKED ISSUE #1371: MapLocationListener is too slow
If you are traveling fast, the location updates of the `MapLocationListener` are slower than those of the `GPSScanner`. As a result, new reports are drawn on the map without the blue user position dot being updated. So it is lagging behind which looks odd.
I think an easy fix would be to make the `MapLocationListener` listen to `GPSScanner.ACTION_GPS_UPDATED` intents.

stumbler

### PR DESCRIPTION
**Pull request by cascheberg**
Fixes #1371

### CODE REVIEW

**Comment by garvankeeley** [comment]
Except now there would be a GPS listener, a network listener, AND a passive listener. I don't think all 3 are needed. The passive listener could get GPS locations, so can the GPS listener be removed?

**Comment by cascheberg** [comment]
I think you could stop this GPS listener while the scanning is active, but that will make the code more complicated without much benefit.
Completely removing the GPS listener here will result in not getting a location if scanning is stopped and Android's network provider is disabled / offline.

**Comment by garvankeeley** [comment]
Agreed, I think 3 are still needed.
- Enable passive listener at all times
- when scanning stopped, enable GPS+network listener

Maybe pauseGpsUpdates() can go away?

**Comment by cascheberg** [comment]
@garvankeeley Your suggestions are basically dealing with code changes in #1589, so I commented there. Maybe you can merge this PR and then continue the discussion there about what "properly configure" actually should be like?

**Pull request merged**
