### PR TITLE
Refactor data storage to common base

### PR DESCRIPTION
**Pull request by garvankeeley**
This is required for leaderboards to re-use the data storage backend.

### CODE REVIEW

**Comment by garvankeeley** [comment]
Getting a test failure with this code:

```
org.mozilla.mozstumbler.service.stumblerthread.ReporterTest > testReporterCellLimits STANDARD_OUT
    E/ACRA: Failed to send crash reports for 0-IS_SILENT.stacktrace
    java.lang.NullPointerException
        at org.acra.ACRA.isDebuggable(ACRA.java:306)
        at org.acra.SendWorker.sendCrashReport(SendWorker.java:175)
        at org.acra.SendWorker.checkAndSendReports(SendWorker.java:141)
        at org.acra.SendWorker.run(SendWorker.java:77)
    W/ACRA: Could not delete error report : 0-IS_SILENT.stacktrace
    D/ACRA: #checkAndSendReports - finish
    W/ACRA: ACRA#init called more than once. Won't do anything more.
    I/Stumbler_MainApp: Simulation disabled as developer option is not enabled.
    i: Stumbler_StorageManager, Preparing to write to : [/var/folders/qm/lt75scjd1hj_vmb2zgj7qx1r0000gn/T/android-external-cache1514350942196046180robolectric/65943ab0-cf95-48ab-8d24-ca92666d29a1/_mock_files_dir/reports/report-t1431386499004-r0-w0-c0.gz]
    E: Stumbler_StorageManager, Error writing reports to disk: java.io.IOException: No such file or directory
    D/ACRA: Using default Report Fields
    E/ACRA: DumpSysCollector.meminfo could not retrieve data
    java.io.IOException: Cannot run program "dumpsys": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:485)
        at org.acra.collector.DumpSysCollector.collectMemInfo(DumpSysCollector.java:51)
        at org.acra.collector.CrashReportDataFactory.createCrashData(CrashReportDataFactory.java:200)
        at org.acra.ErrorReporter.handleException(ErrorReporter.java:653)
        at org.acra.ErrorReporter.handleSilentException(ErrorReporter.java:427)
        at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.JSONRowsStorageManager.saveToDisk(JSONRowsStorageManager.java:204)
        at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.JSONRowsStorageManager.saveAllInMemoryToDisk(JSONRowsStorageManager.java:238)
        at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.JSONRowsStorageManager.insertRow(JSONRowsStorageManager.java:253)
        at org.mozilla.mozstumbler.service.stumblerthread.datahandling.DataStorageManager.insert(DataStorageManager.java:152)
        at org.mozilla.mozstumbler.service.stumblerthread.Reporter.flush(Reporter.java:199)
        at org.mozilla.mozstumbler.service.stumblerthread.Reporter.onReceive(Reporter.java:146)
        at org.mozilla.mozstumbler.service.stumblerthread.ReporterTest.testReporterCellLimits(ReporterTest.java:161)
```

**Comment by crankycoder** [comment]
That's a bad path with robolectric.  Just disable the test for now and we
can look at it later.  I'd like to bump to robolectric 3 anyway as that
seems to be stable now.

**Comment by garvankeeley** [comment]
Notes:
- we can go over how to split this into separate issues if needed. I just want you to see where this is going.
- the last commit doesn't have the server address specified for the leaderboard server, so that is a TODO
- needs TESTS TESTS TESTS

**Comment by garvankeeley** [comment]
I'll update with your nits addressed, but other than that I am happy with this and would like to see it land if possible. The next step is time-consuming, which is to build up the test framework for the leaderboard code.

**Comment by crankycoder** [comment]
Review is done.

**Pull request merged**
