### PR TITLE
GPS displayed on MapActivity

### LINKED ISSUE #484: Show two markers on MapActivity: One for GPS, one for Mozilla Location Service
To get a grasp, on how precise the location service is working, the MapActivity should show an additional Marker for the GPS fix.
For this, two new variables (e.g. mLatGps, mLonGps) would be needed in src/org/mozilla/mozstumbler/MapActivity.java and filled on startup.

### PR DESCRIPTION
**Pull request by tamcap**
This would close #484.
- I actually didn't like the "marker" so I left it out from 2ccb882, but I can revert to 6d058f5 if desired. Not too happy with the design, so give me your ideas.
- It right now uses GPS intents (minimizes codebase impact), which makes it behave... spottily at start, screen turn, etc. It might have to be re-implemented through the AIDL communication instead.

Comments welcome.

### CODE REVIEW

**Comment by tamcap** [comment]
preview

**Comment by Djfe** [comment]
Why is the pointer offset? (circle's position is top-right from the pointer)
Or is the pointer the accurate GPS position (I don't think so)

**Comment by tamcap** [comment]
The latest commit has no pointer ;-)

**Comment by tamcap** [comment]
The circle you see is the GPS accuracy. We might have to show it differently...

**Comment by Djfe** [comment]
What do you think about showing two markers on the map? #484
Or maybe a pointer for GPS (maybe including a circle) and a circle for the MLS location guess and accuracy

**Comment by tamcap** [comment]
This could be a good idea. A marker for GPS, and an accuracy circle for MLS.

**Comment by tamcap** [comment]
It looks nice... but I am afraid the GPS/MLS difference might be confusing...

**Comment by Djfe** [comment]
We could add a map legend to make it clear.

Later on we could enhance the legend when the map shows estimated cell tower positions. (a new pointer/circle/etc.)

**Comment by vinitraje** [comment]
Same method is used by Google/Nokia for their maps. A marker for exact location and a circle for network based location.

**Comment by cpeterso** [comment]
@tamcap: what are your thoughts on this pull request? After you first posted it, you told me on IRC that you would like to think about for a few more days, so I haven't merged it yet. :)

**Comment by tamcap** [comment]
Please don't merge yet. I need to try different designs :-)

**Comment by cpeterso** [comment]
@tamcap: I added a "DO NOT MERGE YET" reminder to this pull request's title. When you're ready, you can just change the title back.

**Comment by tamcap** [comment]
Any design feedback? :) What do you think is the best graphical composition
for that? I am really trying to keep the map uncluttered.

**Comment by vinitraje** [comment]
@tamcap can you add overlay text on the marker and circle indicating GPS and Network based location? It will be easy to understand.

**Comment by cpeterso** [comment]
@tamcap: I removed the map pointer in an earlier version of MozStumbler, but after some user feedback, I think knowing the exact (predicted) position is useful for debugging and calibrating the server's location algorithms.

**Comment by tamcap** [comment]
OK. Very interesting feedback. I will close this PR and rework it. Expect a new PR relatively soon.

**Pull request closed without merging**
