### PR TITLE
Marathi Translation

### PR DESCRIPTION
**Pull request by vinitraje**
Marathi translation of MozStumbler

### CODE REVIEW

**Comment by cpeterso** [comment]
Thanks for the new translation, @vinitraje! When you have completed your work, can you please squash all your commits into one commit that creates the `res/values-mr/strings.xml` file? To keep the commit history tidy, we don't want to merge branches that have many work-in-progress commits.

**Comment by vinitraje** [comment]
Sorry @cpeterso but I don't have idea about squashing commits. I'm still learning to work on Git.
I've finished the translation but don't know how to squash the commits, can you help?

**Comment by cpeterso** [comment]
No problem. I downloaded your branch and used `git rebase --interactive` to squash your branch's give commits into one. Does the squashed code in pull request #231 look correct to you? If so, then I can merge that branch with your changes.

**Comment by vinitraje** [comment]
It looks good

Chris Peterson notifications@github.com wrote:

No problem. I downloaded your branch and used `git rebase --interactive` to squash your branch's give commits into one. Does the squashed code in pull request #231 look correct to you? If so, then I can merge that branch with your changes.

---

**Pull request closed without merging**
