### PR TITLE
Added german translation

### PR DESCRIPTION
**Pull request by DaAllexx**
After several new translations, I thought German was missing ;)

### CODE REVIEW

**Comment by DaAllexx** [comment]
Haven't seen, that's there is already a pull request with a german translation. Never mind, I started yesterday with it, and it seemed, I was too slow :D

**Comment by guerda** [comment]
DaAllexx: I just created it today and pushed it, so I was just more impulsive ;)

**Comment by hannosch** [comment]
On a purely subjective note: I think this translation is slightly better. @cpeterso, you want to merge this one? And then @guerda can suggest changes on this basis.

**Comment by cpeterso** [comment]
LGTM!

**Pull request merged**
