### PR TITLE
Update german (de) translation

### PR DESCRIPTION
**Pull request by r-52**
Synch. german translation with the latest english version.

### CODE REVIEW

**Comment by Djfe** [comment]
<string name="gps_satellites">GPS Satellites Used / Visible: %1$d/%2$d</string>
needs to be updated still
there was a change to the original translation to display used and visible gps satellites

```
<string name="gps_satellites">GPS Satelliten Verwendet/Sichtbar: %1$d</string>
```

A few other things I wanted to change anyways:

```
<string name="view_leaderboard">Bestenliste ansehen</string>
<string name="view_map">Mozillas Ortungsdienst testen</string>
<string name="activity_recognition_service">Mozilla Stumbler Intentions-Dienst zur Aktivitätserkennung</string>
<string name="last_upload_time">Letzter Upload: %1$s</string>
<string name="reports_sent">Gesendete Berichte: %1$d</string>
<string name="service_scanning">Scanne nach Wi-Fi und Mobilfunknetzen</string>
```

We could also use "Spitzname" instead of "Name" but "Nickname" is definitely not German:

```
<string name="enter_nickname">Namen eingeben (optional)</string>
<string name="enter_nickname_title">Name: </string>
<string name="enter_nickname_longtext">Dieser Name wird in der Bestenliste erscheinen.</string>
```

```
<string name="update_now">Jetzt aktualisieren</string>
<string name="update_later">Später aktualisieren</string>
<string name="gps_alert_msg">GPS ist ausgeschaltet. Wollen Sie die Einstellungen aufrufen, um es einzuschalten?</string>
<string name="about_mapbox">Mehr über unseren Kartenanbieter erfahren…</string>
<string name="about_legal_aosp">Einige Symbole in dieser Anwendung wurden Werken entnommen, welche vom Android Open Source Project erstellt und verteilt werden. Sie werden in Übereinstimmung mit der Creative Commons - Attribution 2.5 Lizenz verwendet.</string> (One dot too much at the end of the sentence: there were two: "..")
<string name="upload_observations_sent_title">Gesendet</string>
<string name="upload_observations_last_upload_time_title">Letzter Upload:</string>
<string name="upload_observations_wifis_sent_title">Wi-Fi Zugangspunkte:</string>
<string name="upload_observations_in_queue_title">Warteschlange</string>
<string name="upload_observations_wifis_queued_title">Wi-Fi Zugangspunkte:</string>
<string name="upload_observations_dialog_title">Beobachtungen hochladen</string>
<string name="upload_wifi_only_summary">Diese Option reduziert den Datenverbrauch im Mobilfunknetz.</string>
<string name="geofencing_explain">Das Geofencing wird an dem nächsten, gültigen, während des Scannens erhaltenen Standort festgelegt werden.</string>
<string name="geofencing_off">Geofencing: Aus</string>
<string name="geofencing_desc">MozStumbler wird den Scanvorgang im Umkreis von 1 km um den oben angegebenen Standort (Breiten-/Längengrad) unterbrechen.</string>
<string name="geofencing_on">Geofencing @ %1$.3f/%2$.3f</string>
<string name="geofencing_enable">Geofencing für diesen Standort.</string>
```

I don't think there is a way for me do edit his version, is there?
Github just complains I'm not on the same branch
does that mean I don't have any writing permission?

**Comment by r-52** [comment]
I added you to my Collaborators list. You should now be able to push/ pull against my fork and the pull request branch.

**Comment by Djfe** [comment]
Just got informed about that by a notification e-mail, thx for that ;)
I will propose my changes later.
What would you prefer:
"Name" or "Spitzname" as a translation for nickname?

**Comment by r-52** [comment]
Take your time for the changes.

Mhhhhh... "Spitzname" is one word that seems to be replaced by some anglicisms like "username" or "user". The german translation contains non-german words like "geofencing" so I would choose "name" or something like "Benutzername". On the other side, "Spitzname" would be a rare (positive) surprise :)

**Comment by Djfe** [comment]
I thought about a way to translate it but geofencing seems to be a "Fachbegriff"
Even Wikipedia uses that word
"Einen Zaun aufstellen" doesn't fit
We could translate it freely "Sperrgebiet" or something like that
But users shouldn't have problems with that word as there is an explanation for it below and a quick Google search shows further explanations on Wikipedia

"Benutzername" doesn't fit since you don't make an account (yet -> there are ideas to use Mozilla persona as a login service)

**Comment by Djfe** [comment]
the edit button is still grayed out...

**Comment by r-52** [comment]
Which edit button? The edit button in the right corner of the pull request? I granted you the collaborator rights to push against my pull- request branch.

**Comment by Djfe** [comment]
For me it looks like this:
image

**Comment by Djfe** [comment]
Ahh now I know what is wrong...I needed to change my branch to de-translation :)

**Comment by r-52** [comment]
Excellent! And your translations are great! +1 from me.

**Comment by Djfe** [comment]
Thx :)
This can be merged now

**Comment by cpeterso** [comment]
Looks good! Thanks for your contribution and patience, @romankl, and thanks for your help here, @Djfe. :cake: :)

**Pull request merged**
