### PR TITLE
Show notification when scanning

### PR DESCRIPTION
**Pull request by cpeterso**
The `NotificationCompat.Builder` does not seem to actually do anything on my device, so I resurrected the older, proven `buildNotification()` method that does display the notification icon.

### CODE REVIEW

**Comment by illarionov** [comment]
It does not show icon with NotificationCompat.PRIORITY_MIN by default. You can try to change to NotificationCompat.PRIORITY_LOW or NotificationCompat.PRIORITY_NORMAL.

**Comment by cpeterso** [comment]
@illarionov: I did not realize that. What is the any advantage of using NotificationCompat Builder over just using the "deprecated" Notification API?

**Comment by illarionov** [comment]
I have used NotificationCompat.Builder to set the priority of the notification trying to make it less annoying.
Besides, it allows to use notification features of the newest Android versions without having to worry about compatibility. http://developer.android.com/design/patterns/notifications.html

**Comment by cpeterso** [comment]
That makes sense. I'll revert my change, but I think we do want to display a notification icon if we are running in the background.

We currently only display the notification when the service is actively scanning. However, this means that in power-saving mode we will only show the notification when the user is actively moving. I'd like to change this so we always display the notification icon when the service is running. Otherwise, we might be draining people's batteries, but when they look at their screen, they don't see any notification that might point the blame to our app.

**Pull request merged**
