### PR TITLE
Bump Android build tools and Android support library to version 20

### PR DESCRIPTION
**Pull request by cpeterso**

### CODE REVIEW

**Comment by crankycoder** [comment]
Why are we bumping to add support for Android Wear?

**Comment by Djfe** [comment]
Android wear would provide a great way for checking the current scan stats!
Pretty cool use case in my opinion.

**Comment by cpeterso** [comment]
I bumped the Android build tools and Android support library to their latest versions (simply because they are available), but I did not bump the Android API level. We're still using API level 19 (KK 4.4.2), not level 20 (Android 4.4W or L Preview).

**Comment by crankycoder** [comment]
I would like to defer this change at least until the unittest changes for #629 go in as the gradle build is going to change pretty substantially.  I'm not particularly interested in having people change their build requirements when the most recent API we actually use is API 18 and we have no code that actually requires bumping the support library version up.

**Comment by cpeterso** [comment]
OK

**Pull request closed without merging**
