### PR TITLE
Modify the date format to YYYY-mm-01.

### PR DESCRIPTION
**Pull request by tamcap**
Match the mozilla/ichnaea#120 changes as done by @crankycoder and send the date as `YYYY-mm-01` only (overwriting the day value).

### CODE REVIEW

**Comment by Djfe** [comment]
What about the time of day?
-> seconds, minutes, hours

And does it make sense to replace this on the Client if the Server does that already?

**Comment by tamcap** [comment]
We have removed time of day a while ago. This is a minor fix (in theory) improving privacy client-side and during transmission. I will not be very upset if @cpeterso decides it's redundant, but I like to keep client and server side "matched" to avoid some unexpected behavior down the road.

**Comment by cpeterso** [comment]
I don't think the `formatDate()` method should be printing a different date/time value ("YYYY-MM-01") than the parameter value passed in ("YYYY-MM-DD"). Let the caller mangled the dates before it calls `formatDate()`. Perhaps the "YYYY-MM-DD" → "YYYY-MM-01" conversion should be  encapsulated in a helper method in DateTimeUtils.java?

**Comment by tamcap** [comment]
Let me know what you think.

**Comment by tamcap** [comment]
:+1:

**Comment by cpeterso** [comment]
LGTM! Thanks, @tamcap!

**Pull request merged**
