### PR TITLE
Updated Marathi & Hindi translation

### PR DESCRIPTION
**Pull request by vinitraje**
Updated Marathi & Hindi strings

### CODE REVIEW

**Comment by cpeterso** [comment]
@vinitraje: is this pull request the one I should merge?

**Comment by vinitraje** [comment]
@cpeterso Yes. It is. Sorry for the other requests, sometimes I get confused with github.

**Comment by vinitraje** [comment]
The other requests had error on Travis. This one passed. ;)

**Comment by cpeterso** [comment]
No problem. This pull request looks good. Thanks again!

**Pull request merged**
