### PR TITLE
Remove ocpsoft PrettyTime dependency

### PR DESCRIPTION
**Pull request by cascheberg**
Implement custom `PrettyTime` replacement, see #1066 
@garvankeeley What do you think about this?

### CODE REVIEW

**Comment by hannosch** [comment]
It looks like you are providing a singular / plural message for each of the "pretty times". Unfortunately different languages have very different rules on how to change a text based on the number of items they refer to. Many languages have multiple plural forms, with complex rules for when to apply them.

If you want to get into the details, the gettext suite and their po/mo format solves a lot of these. See for example https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html. I'm not really familiar with Android development, so I'm not sure if there's a way to encode these sort of complex plural forms into the translation system.

**Comment by hannosch** [comment]
And of course a simple google search reveals: http://developer.android.com/guide/topics/resources/string-resource.html#Plurals

**Comment by cascheberg** [comment]
Thanks for the information!
I was wondering if that could be a problem, but I checked and PrettyTime is not supporting this either (or I just totally missed it).
Update: That should be easy to implement if the push is ok in general.

**Comment by garvankeeley** [comment]
+1 to this.
Can you add plurals.xml (or whatever it is called) for english so others will see how to add plurals for other languages.

**Comment by cascheberg** [comment]
PR updated to use Android quantity strings for plural forms.
Note that the feature is still only enabled for `en` locales.

**Comment by garvankeeley** [comment]
Tested, works great. Can you merge/rebase and I'll land it? Thanks.

**Comment by cascheberg** [comment]
Merged

**Pull request merged**
