### PR TITLE
Pull blocklist from web #581

### PR DESCRIPTION
**Pull request by anishgkanchan**

### CODE REVIEW

**Comment by garvankeeley** [comment]
I pulled your branch and it did build, still we need to find out why this won't build before it gets into the codebase. We depend on Travis. The prolog of blocklist.txt is the problem, perhaps it needs to be a .json file and properly declared as such in the first line. Not sure

**Comment by garvankeeley** [comment]
The Blocklist is getting downloaded, but where is it being applied? Probably the code is there somewhere, but because of all the commits being split up, I would have to go digging for it. 
(BTW, I made this mistake plenty of times!)

**Comment by anishgkanchan** [comment]
Would you please tell me how I'm supposed to use the blocklist downloaded? One way would be to add a method in SSIDBlocklist.java which would read the blocklist.

**Comment by cpeterso** [comment]
hi @anishgkanchan, are you still working on this downloadable blocklist feature? I spoke with @garvankeeley offline and I think this feature might be more complicated than what we need. While we do update the SSID blocklist more often (from contributors' pull requests) than we release new MozStumbler builds, I don't think waiting until the next MozStumbler release to get the new blocklist is a big problem.

**Comment by anishgkanchan** [comment]
@chrispeterson actually I was working on it but then @garvankeeley told me
that I could work on it later because I was a bit hazy on it's further
implementation.
So I started reading up on the 'Display the user's "tracks" on
MozStumbler's map issue.
Later after an Android Studio update the 'MozStumbler' project stopped
building altogether due to some Gradle issue.
Do you suggest that I don't work on the 'Pull blocklist' issue any further?

Regards,
Anish Kanchan
Student, University of Mumbai

**Comment by cpeterso** [comment]
hi @anishgkanchan, since you were blocked on the implementation, I think there are other MozStumbler features you could work on that would have more immediate benefit for users.

I think issue #664 ("Move SSID blocklist from Java code to user-configurable text file on /sdcard") might be an interesting bug for you because you are already familiar with the SSID blocklist code. If we move the blocklist from Java code to the sdcard, then people could edit it on their own devices. They could add private SSIDs to their blocklist or even remove the default SSIDs. :)

I'm going to closed this PR for now. If you have any questions, just add an @cpeterso question in the issue or, better yet, drop by the #geo IRC channel on irc.mozilla.org.

**Comment by anishgkanchan** [comment]
The  'Move SSID blocklist from Java code to user-configurable text file on
/sdcard' issue was closed few days back.
I had already done some work on it before. I wished to know if that portion has already been coded.
I'd like to work on it.

**Comment by crankycoder** [comment]
@anishgkanchan  there is no code for this yet.

**Comment by anishgkanchan** [comment]
Yes cool. I'll continue my work on issue #664.

**Pull request closed without merging**
