### PR TITLE
Adding strings for spanish language.

### PR DESCRIPTION
**Pull request by matagus**

### CODE REVIEW

**Comment by dougt** [comment]
Hey Matagus,

Can you review the strings from https://github.com/dougt/MozStumbler/pull/179?

**Comment by cpeterso** [comment]
hi @matagus: Can you please rebase your pull request on top of the latest master? I think your pull request has a merge conflict with recent Spanish strings changes. Thanks!

**Comment by matagus** [comment]
@cpeterso done!

(I'm not sure if it makes sense to merge it since you merged #179 before this, even when this PR was older)

**Comment by cpeterso** [comment]
Thanks, @matagus! Sorry I missed this PR before merging the other one! We had a lot of new PRs and issues.

btw, what is the difference between "las configuraciones" and "la configuración"? When is one phrase more appropriate than the other?

**Comment by matagus** [comment]
np @cpeterso 

the difference is that in spanish we use to say "configuración" (singular noun) not "configuraciones"(plural) while in english you use "settings" (plural)

**Pull request merged**
