### PR TITLE
On first start use last known location

### PR DESCRIPTION
**Pull request by cascheberg**
The last know location is set by `MapLocationListener` when calling `MapFragment.onResume()`.

### CODE REVIEW

**Comment by crankycoder** [comment]
I'm going to be the party pooper here and start clamping down on all features without test cases. We're moving to having an automated test as a requirement to landing a patch.

**Comment by cascheberg** [comment]
I know that automated tests are really great to have, I just need to figure out how to write them here.

**Comment by crankycoder** [comment]
@cascheberg - can you rebase this so that it merges cleanly?  I'm going to hold off on requiring test cases until my own test branch merges and we have proper documentation on how to write good tests.

**Comment by cascheberg** [comment]
@crankycoder Ok cool, done.

**Comment by crankycoder** [comment]
@garvankeeley this looks ok to me.  Can you take a look and merge?

**Comment by garvankeeley** [comment]
LGTM.

**Pull request merged**
