### PR TITLE
Fix for 1484, on startup update the last upload in the notification

### PR DESCRIPTION
**Pull request by garvankeeley**
See #1484

### CODE REVIEW

**Comment by crankycoder** [comment]
reviewed this in IRC

**Comment by garvankeeley** [comment]
@crankycoder r? 
This should be a minimal way of fixing this without affecting your refactor.

**Comment by cascheberg** [comment]
Now the notification is always shown, and it is not going away if the stumbler is stopped or even killed. This is probably because it is calling `update` once after the stumbler has stopped.
Do I need to reboot my device now to get rid of it? I think a quick fix would be great.

**Comment by garvankeeley** [comment]
Thanks @cascheberg 
This should fix it https://github.com/mozilla/MozStumbler/pull/1553

**Pull request merged**
