### PR TITLE
1176 Write stumbles to disk on low memory notification

### PR DESCRIPTION
**Pull request by garvankeeley**
#1176

Handle OS low memory notifications and call DataStorageManager saveCurrentReportsToDisk()

### CODE REVIEW

**Comment by crankycoder** [comment]
Is there a way to test this at all using adb?

**Comment by garvankeeley** [comment]
There doesn't appear to be a way to directly send low memory in adb .

**Comment by SteveALee** [comment]
How about 'adb shell' and then run 'ulimit' ?

**Comment by garvankeeley** [comment]
Great suggestion! will try...

**Pull request merged**
