### PR TITLE
Remove batch processing logic from Reporter

### PR DESCRIPTION
**Pull request by illarionov**
Save each observation as a single row in the database ('Reports' table).

I'm also restored reporting of wifis and cells in one observation, since memory should not be a problem now.

### CODE REVIEW

**Comment by Djfe** [comment]
Looks interesting ;)
Thx for the change

One question to how observations will be counted from now on:
4 wifi aps + 4 cell towers = 4 observation
Or:    "  "  = 8 observations
Are you counting them together or alone?

**Comment by cpeterso** [comment]
LGTM! :)

**Comment by tamcap** [comment]
I just got hit by a `NullPointerException`:

02-20 13:03:18.782    7718-7739/org.mozilla.mozstumbler:.ScannerService E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-16347
    Process: org.mozilla.mozstumbler:.ScannerService, PID: 7718
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.location.Location.setTime(long)' on a null object reference
            at org.mozilla.mozstumbler.Reporter.reportCollectedLocation(Reporter.java:177)
            at org.mozilla.mozstumbler.Reporter.flush(Reporter.java:68)
            at org.mozilla.mozstumbler.ScannerService$1$2.run(ScannerService.java:90)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at org.mozilla.mozstumbler.ScannerService$LooperThread.run(ScannerService.java:154)

**Comment by tamcap** [comment]
Hmm. Now it's gone. Let's keep it in the back of our heads for now.

**Comment by Djfe** [comment]
Maybe it happens once because the database got recreated (v2).
Then you couldn't reproduce it without a database v1.

Maybe you can reproduce it by reinstalling v0.13.0 and then updating again

**Comment by cpeterso** [comment]
But GPSScanner.java looks like it would never send a `GPS_SCANNER_ARG_LOCATION` intent with a null `Location` (because `GPSScanner.onLocation()` would crash with its own NullPointerException first).

**Comment by tamcap** [comment]
The problem is, it happens very randomly... I can't willingly reproduce it despite my best efforts.

**Comment by tamcap** [comment]
My best bet is something, somewhere, calls a `new Reporter()` (which results in implicit setting of `mGpsPosition = null`)  while `reportCollectedLocation()` is running.

**Pull request merged**
